### PR TITLE
Fix _os.platform is not a function error

### PR DESCRIPTION
**Pull request by aluanhaddad**
This fixes the `_os.platform is not a function` exception which occurs when attempting to use the bundle command in jspm@0.17.0-beta. I experimented with local overrides and this did the trick. @frankwallis, @guybedford, does this look right? I was able to reproduce the issue on multiple systems. typescript@1.8.10 works fine with jspm@0.17.0-beta, and typescript@1.9.0-dev works fine when building with jspm@0.16.35.

### CODE REVIEW

**Comment by frankwallis** [comment]
Yes I think that is correct

**Comment by guybedford** [comment]
Thanks @frankwallis for the confirmation here.

**Comment by aluanhaddad** [comment]
Thanks!
